'use client'
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { persistor, store } from "@/redux/store";
import Head from "next/head";
// import { NextAuthProvider } from "./Providers";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"]})

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>
          Provirals
        </title>
      </head>
      <body className={openSans.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            {/* <NextAuthProvider> */}
              {children}
            {/* </NextAuthProvider> */}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
